<a href="https://colab.research.google.com/github/MariaNikolaeva2028/Japanese-Candlestick-Chart/blob/main/Japanese_Candlestick_Chart_20_09_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Обоснование: на основе данных о котировках контракта SPFB.RTS-12.18 (RIZ8)за 2018 год необходимо построить  график "японские свечи" для даты 20 сентября и выполнить прогноз направления графика "японские свечи" на 21 сентября.

In [25]:
import pandas as pd

In [26]:
data = pd.read_csv('https://courses.openedu.ru/assets/courseware/v1/824fccdb3e15cab129049a536ece5500/asset-v1:ITMOUniversity+DATANTECH2035+fall_2021_3+type@asset+block/SPFB.RTS-12.18_180901_181231.csv')
data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1
...,...,...,...,...,...,...,...,...,...
58965,SPFB.RTS-12.18,1,20/12/18,18:40,109380.0,109380.0,109380.0,109380.0,1
58966,SPFB.RTS-12.18,1,20/12/18,18:41,109380.0,109390.0,109380.0,109390.0,10
58967,SPFB.RTS-12.18,1,20/12/18,18:43,109380.0,109390.0,109380.0,109390.0,12
58968,SPFB.RTS-12.18,1,20/12/18,18:44,109390.0,109390.0,109390.0,109390.0,3
58969,SPFB.RTS-12.18,1,20/12/18,18:45,109390.0,109390.0,109380.0,109380.0,3

Изменение формата времени: объединение ячеек даты времени и уход от строкового объекта

In [27]:
data['DATE'] = data['<DATE>'] + ' ' + data['<TIME>']
data['DATE'] = pd.to_datetime(data['DATE'], format = "%d/%m/%y %H:%M")
data

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
0,SPFB.RTS-12.18,1,03/09/18,10:01,107900.0,108060.0,107900.0,108030.0,3,2018-09-03 10:01:00
1,SPFB.RTS-12.18,1,03/09/18,10:02,107960.0,107960.0,107960.0,107960.0,5,2018-09-03 10:02:00
2,SPFB.RTS-12.18,1,03/09/18,10:04,108000.0,108000.0,108000.0,108000.0,8,2018-09-03 10:04:00
3,SPFB.RTS-12.18,1,03/09/18,10:05,108000.0,108000.0,108000.0,108000.0,1,2018-09-03 10:05:00
4,SPFB.RTS-12.18,1,03/09/18,10:08,108080.0,108080.0,108080.0,108080.0,1,2018-09-03 10:08:00
...,...,...,...,...,...,...,...,...,...,...
58965,SPFB.RTS-12.18,1,20/12/18,18:40,109380.0,109380.0,109380.0,109380.0,1,2018-12-20 18:40:00
58966,SPFB.RTS-12.18,1,20/12/18,18:41,109380.0,109390.0,109380.0,109390.0,10,2018-12-20 18:41:00
58967,SPFB.RTS-12.18,1,20/12/18,18:43,109380.0,109390.0,109380.0,109390.0,12,2018-12-20 18:43:00
58968,SPFB.RTS-12.18,1,20/12/18,18:44,109390.0,109390.0,109390.0,109390.0,3,2018-12-20 18:44:00
58969,SPFB.RTS-12.18,1,20/12/18,18:45,109390.0,109390.0,109380.0,109380.0,3,2018-12-20 18:45:00

Выборка по дате 20 сентября 2018.

In [28]:
data_filtered = data[data['DATE'].dt.strftime('%Y-%m-%d') == '2018-09-20']
data_filtered

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,DATE
6725,SPFB.RTS-12.18,1,20/09/18,10:01,112090.0,112730.0,111950.0,112390.0,3190,2018-09-20 10:01:00
6726,SPFB.RTS-12.18,1,20/09/18,10:02,112390.0,112430.0,112340.0,112400.0,979,2018-09-20 10:02:00
6727,SPFB.RTS-12.18,1,20/09/18,10:03,112400.0,112420.0,112340.0,112420.0,779,2018-09-20 10:03:00
6728,SPFB.RTS-12.18,1,20/09/18,10:04,112410.0,112550.0,112380.0,112500.0,1658,2018-09-20 10:04:00
6729,SPFB.RTS-12.18,1,20/09/18,10:05,112490.0,112540.0,112450.0,112510.0,977,2018-09-20 10:05:00
...,...,...,...,...,...,...,...,...,...,...
7524,SPFB.RTS-12.18,1,20/09/18,23:46,112740.0,112750.0,112730.0,112730.0,391,2018-09-20 23:46:00
7525,SPFB.RTS-12.18,1,20/09/18,23:47,112720.0,112730.0,112700.0,112720.0,129,2018-09-20 23:47:00
7526,SPFB.RTS-12.18,1,20/09/18,23:48,112730.0,112740.0,112720.0,112730.0,253,2018-09-20 23:48:00
7527,SPFB.RTS-12.18,1,20/09/18,23:49,112730.0,112750.0,112660.0,112670.0,517,2018-09-20 23:49:00
7528,SPFB.RTS-12.18,1,20/09/18,23:50,112670.0,112750.0,112650.0,112690.0,314,2018-09-20 23:50:00

Для удобства чтения дата стала индексом объекта

In [29]:
data_filtered = data_filtered.set_index('DATE')
data_filtered

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
DATE,,,,,,,,,
2018-09-20 10:01:00,SPFB.RTS-12.18,1,20/09/18,10:01,112090.0,112730.0,111950.0,112390.0,3190
2018-09-20 10:02:00,SPFB.RTS-12.18,1,20/09/18,10:02,112390.0,112430.0,112340.0,112400.0,979
2018-09-20 10:03:00,SPFB.RTS-12.18,1,20/09/18,10:03,112400.0,112420.0,112340.0,112420.0,779
2018-09-20 10:04:00,SPFB.RTS-12.18,1,20/09/18,10:04,112410.0,112550.0,112380.0,112500.0,1658
2018-09-20 10:05:00,SPFB.RTS-12.18,1,20/09/18,10:05,112490.0,112540.0,112450.0,112510.0,977
...,...,...,...,...,...,...,...,...,...
2018-09-20 23:46:00,SPFB.RTS-12.18,1,20/09/18,23:46,112740.0,112750.0,112730.0,112730.0,391
2018-09-20 23:47:00,SPFB.RTS-12.18,1,20/09/18,23:47,112720.0,112730.0,112700.0,112720.0,129
2018-09-20 23:48:00,SPFB.RTS-12.18,1,20/09/18,23:48,112730.0,112740.0,112720.0,112730.0,253
2018-09-20 23:49:00,SPFB.RTS-12.18,1,20/09/18,23:49,112730.0,112750.0,112660.0,112670.0,517
2018-09-20 23:50:00,SPFB.RTS-12.18,1,20/09/18,23:50,112670.0,112750.0,112650.0,112690.0,314

Оставим только необходимые столбцы и переименуем их

In [30]:
data_filtered = data_filtered[['<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>']]
data_filtered.columns = ['open', 'high', 'low', 'close']
data_filtered

                         open      high       low     close
DATE
2018-09-20 10:01:00  112090.0  112730.0  111950.0  112390.0
2018-09-20 10:02:00  112390.0  112430.0  112340.0  112400.0
2018-09-20 10:03:00  112400.0  112420.0  112340.0  112420.0
2018-09-20 10:04:00  112410.0  112550.0  112380.0  112500.0
2018-09-20 10:05:00  112490.0  112540.0  112450.0  112510.0
...                       ...       ...       ...       ...
2018-09-20 23:46:00  112740.0  112750.0  112730.0  112730.0
2018-09-20 23:47:00  112720.0  112730.0  112700.0  112720.0
2018-09-20 23:48:00  112730.0  112740.0  112720.0  112730.0
2018-09-20 23:49:00  112730.0  112750.0  112660.0  112670.0
2018-09-20 23:50:00  112670.0  112750.0  112650.0  112690.0

[804 rows x 4 columns]

In [31]:
data_aggregation = data_filtered.resample('1H').agg({'open':'first',
                                                     'high':'max',
                                                     'low':'min',
                                                     'close':'last'})

In [32]:
data_aggregation.head()

                         open      high       low     close
DATE
2018-09-20 10:00:00  112090.0  112850.0  111950.0  112670.0
2018-09-20 11:00:00  112670.0  113170.0  112620.0  112910.0
2018-09-20 12:00:00  112910.0  113850.0  112910.0  113270.0
2018-09-20 13:00:00  113280.0  113930.0  112960.0  113860.0
2018-09-20 14:00:00  113860.0  114060.0  112950.0  113050.0

Визуализация агрегированных данных "японские свечи"

In [33]:
import plotly.graph_objects as go

In [34]:
figure = go.Figure(data=[go.Candlestick(x=data_aggregation.index,
                                        open=data_aggregation['open'],
                                        high=data_aggregation['high'],
                                        low=data_aggregation['low'],
                                        close=data_aggregation['close'])])
figure.update_layout(
    title='Данные о котировках контракта SPFB.RTS-12.18 (RIZ8) за 20.09.18')
figure.show()

Полученные график "японские свечи" за 20 сентября 2018 года в промежутке с 10.00 до 13.00 отображает бычье движение, за которым следует свечной  паттерн разворота "три черных вороны": показатель нисходящего тренда. Опираясь на данные в промежуток с 21.00 до 22.00 можно говорит о наличии разворотного паттерна "нижняя часть пинцета", исходя из которого можно планировать восходящий тренд на 21 сентября 2018г.

Проверим данное предположение и построим график "японские свечи" за 20 сентября 2018 года.

In [35]:
data_filtered_test_data = data[data['DATE'].dt.strftime('%Y-%m-%d') == '2018-09-21']
data_filtered_test_data = data_filtered_test_data.set_index('DATE')
data_filtered_test_data = data_filtered_test_data[['<OPEN>', '<HIGH>', '<LOW>', '<CLOSE>']]
data_aggregation_test_data = data_filtered_test_data.resample('1H').agg({'<OPEN>':'first',
                                                     '<HIGH>':'max',
                                                     '<LOW>':'min',
                                                     '<CLOSE>':'last'})
import plotly.graph_objects as go
figure_test_data = go.Figure(data=[go.Candlestick(x=data_aggregation_test_data.index,
                                        open=data_aggregation_test_data['<OPEN>'],
                                        high=data_aggregation_test_data['<HIGH>'],
                                        low=data_aggregation_test_data['<LOW>'],
                                        close=data_aggregation_test_data['<CLOSE>'])])
figure_test_data.update_layout(
    title='Данные о котировках контракта SPFB.RTS-12.18 (RIZ8) за 21.09.18')
figure_test_data.show()

Опираясь на полученный график можно говорить о том, что выдвинутое предположение верно и в промежутке с 10 до 11.00 наблюдается бычье движенье. В целом, по данным за 21 сентября 2018 года быки отправляют рынок вверх.